회원정보수정이 현재는 완료된 상태이지만, 서비스하기에는 불안하다.

![Visual Studio Code](/img/%ED%9A%8C%EC%9B%90%EC%A0%95%EB%B3%B4%EC%88%98%EC%A0%95.png)

why?

현재 수정 시 name과 password를 무조건 받아야함.

password를 안받으면 DB에 공백값이 들어가지니까.

(1)name과 password가 안들어오는것을 막으려면 앞단에서 막아주면된다. (유효성검사)

(2)그리고 프론트단에서도 막아주면된다(프론트단)

=> 얘네는 DB에 접근안해도 확인할 수 있는 부분
=> 그래서 얘네는 앞단에서 처리

---

1번유저를 수정하려고 하는데 영속화를 시켜놨더니 1번유저가 없음. => 이러면 또 수정안됨.

=> 얘네는 DB에 접근해야 확인 가능한 부분
=> 그래서 얘네는 뒷단에서 처리

---

(update.js)

```
<form id="profileUpdate" onsubmit="update(${principal.user.id})">

	<input type="text" name="name" placeholder="이름"
							value="${principal.user.name}" required="required"/>


    <div class="item__title">패스워드</div>
					<div class="item__input">
						<input type="password" name="password" placeholder="패스워드" required="required"/>
					</div>
~

<button>제출</button>
```

이름과 패스워드에 required="required"를 적용함으로써 필수로 있어야한다는 유효성이 체크되게 하기위해선 button에 type="button"으로 있을것이아니라 form태그에 submit으로 제출이 되게 처리해주어야한다.

(update.js)

```
	$.ajax({
		type:"put",
		url:`/api/user/${userId}`,
		data:data,
		contentType:"application/x-www-form-urlencoded; charset=utf-8",
		dataType:"json" //응답은 json으로 받음
	}).done(res=>{ // res에 응답된데이터(json)가 파싱되서 들어옴, 그래서 res는 자바스크립트 오브젝트가 될 것임
		console.log("성공");
		location.href = `/user/${userId}`;
	}).fail(error=>{
		console.log("실패");
	});
```

근데 이렇게 하고나니 ajax에 성공시
location.href=`/user/${userId} 이부분의 페이지 로케이션이 일어나지않는다.

원인은 button클릭시 form 태그를 타게되면 action이 설정되어있지않으면 form기본속성으로 자기자신 페이지로 돌아가게 되있기 때문이다.

해결방법은 update.jsp에서

```
<form id="profileUpdate" onsubmit="update(${principal.user.id},event)">
```

event 파라미터를 추가적으로 던져서

(update.js)

```
function update(userId,event) {

	event.priventDefault(); // form태그 액션을 막기
	/* form 태크를 집어와서 .serialize(); 해주면 모든 input값들이 data에 담기게된다*/
	let data = $("#profileUpdate").serialize();


	$.ajax({
		type:"put",
		url:`/api/user/${userId}`,
		data:data,
		contentType:"application/x-www-form-urlencoded; charset=utf-8",
		dataType:"json" //응답은 json으로 받음
	}).done(res=>{ // res에 응답된데이터(json)가 파싱되서 들어옴, 그래서 res는 자바스크립트 오브젝트가 될 것임
		console.log("성공");
		location.href = `/user/${userId}`;
	}).fail(error=>{
		console.log("실패");
	});
}
```

update.js에서 event.priventDefault();를 적어줘서 form태그 액션을 막아주는 것이다.

**여기까지가 (1)프론트단에서 막기 해결**

---

(UserUpdateDto.java)

```
	@NotBlank
	private String name; //필수
	@NotBlank
	private String password; //필수
```

name과 password에 not null 걸어주고,

---

(UserApiController.java)

```
@RequiredArgsConstructor
@RestController
public class UserApiController {

	private final UserService userService;

	@PutMapping("/api/user/{id}")
	public CMRespDto<?> update(
			@PathVariable int id,
			@Valid UserUpdateDto userUpdateDto,BindingResult bindingResult,// 꼭 @Valid가 적혀있는 "다음"파라미터에 적어야함
			@AuthenticationPrincipal PrincipalDetails principalDetails) {
		System.out.println(userUpdateDto);
		User userEntity = userService.회원수정(id, userUpdateDto.toEntity());
		principalDetails.setUser(userEntity);//세션정보변경
		return new CMRespDto<>(1,"회원수정완료",userEntity);
	}
}
```

@Valid UserUpdateDto userUpdateDto,

@Valid넣어서 검증해서 문제가 생기면

BindingResult bindingResult,

bindingResult에 담겨진다.

---

AuthController.java에서

```
if(bindingResult.hasErrors()) { // bindingResult에 에러가 있다는건

			Map<String,String> errorMap = new HashMap<>();

			for(FieldError error : bindingResult.getFieldErrors()) { //getFieldErrors()는 list를 리턴
				errorMap.put(error.getField(), error.getDefaultMessage());
				System.out.println("here"+error.getDefaultMessage());
			}
			//return "오류남";
			throw new CustomValidationException("유효성검사실패함",errorMap);
		}
```

이 부분만 복사해서

(UserApiController.java)

```
@RequiredArgsConstructor
@RestController
public class UserApiController {

	private final UserService userService;

	@PutMapping("/api/user/{id}")
	public CMRespDto<?> update(
			@PathVariable int id,
			@Valid UserUpdateDto userUpdateDto,
			BindingResult bindingResult, // 꼭 @Valid가 적혀있는 "다음"파라미터에 적어야함
			@AuthenticationPrincipal PrincipalDetails principalDetails) {

		if(bindingResult.hasErrors()) { // bindingResult에 에러가 있다는건

			Map<String,String> errorMap = new HashMap<>();

			for(FieldError error : bindingResult.getFieldErrors()) { //getFieldErrors()는 list를 리턴
				errorMap.put(error.getField(), error.getDefaultMessage());
				System.out.println("here"+error.getDefaultMessage());
			}
			//return "오류남";
			throw new CustomValidationException("유효성검사실패함",errorMap);
		}

		System.out.println(userUpdateDto);
		User userEntity = userService.회원수정(id, userUpdateDto.toEntity());
		principalDetails.setUser(userEntity);//세션정보변경
		return new CMRespDto<>(1,"회원수정완료",userEntity);
	}
}
```

짠~ 하고 넣어줌

![Visual Studio Code](/img/apicontroller.png)
저부분 CustomValidationException부분

CustomValidationApiException새로 만들어서 바꿔줄꺼임.

CustomValidationException은 현재 ControllerExceptionHandler.java에서

    return Script.back(e.getErrorMap().toString());

    를 리턴해서 클라이언트에게 화면을 띄워주도록 처리가 되어있음.

![Visual Studio Code](/img/apiException.png)

ajax통신에서는 이렇게 개발자가 사용하기 편한 데이터로 응답받을 것이기 때문에

CustomValidationApiException에서는 CMRespDto를 응답받는식으로 고쳐준다.

![Visual Studio Code](/img/apicontroller2.png)

여기서 익셉션 발동시킬 때

throw new CustomValidationApiException() 으로 처리

최종

```
@RequiredArgsConstructor
@RestController
public class UserApiController {

	private final UserService userService;

	@PutMapping("/api/user/{id}")
	public CMRespDto<?> update(
			@PathVariable int id,
			@Valid UserUpdateDto userUpdateDto,
			BindingResult bindingResult, // 꼭 @Valid가 적혀있는 "다음"파라미터에 적어야함
			@AuthenticationPrincipal PrincipalDetails principalDetails) {

		if(bindingResult.hasErrors()) { // bindingResult에 에러가 있다는건

			Map<String,String> errorMap = new HashMap<>();

			for(FieldError error : bindingResult.getFieldErrors()) { //getFieldErrors()는 list를 리턴
				errorMap.put(error.getField(), error.getDefaultMessage());
				System.out.println("here"+error.getDefaultMessage());
			}
			//return "오류남";
			throw new CustomValidationApiException("유효성검사실패함",errorMap);
		}else {
			System.out.println(userUpdateDto);
			User userEntity = userService.회원수정(id, userUpdateDto.toEntity());
			principalDetails.setUser(userEntity);//세션정보변경
			return new CMRespDto<>(1,"회원수정완료",userEntity);
		}


	}
}
```

@Valid 걸리지않고, 정상이면 else문 코드 실행

![Visual Studio Code](/img/%EC%9C%A0%ED%9A%A8%EC%84%B1%EA%B2%80%EC%82%AC.png)

이건 성공시

실패 테스트는 update.js에서 이름 부분에 required="required"프론트단꺼 잠깐 지우고 null로 넣어서 어떻게 뜨는지 확인해보자

![Visual Studio Code](/img/%EC%9C%A0%ED%9A%A8%EC%84%B1%EA%B2%80%EC%82%AC2.png)

![Visual Studio Code](/img/%EC%9C%A0%ED%9A%A8%EC%84%B1%EA%B2%80%EC%82%AC3.png)

근데 유효성검사는 처리되서 확인됬는데 콘솔에 성공이라는 글씨를 보니 ajax에서는 .fail이 아니라 .done으로 처리되서 응답이 성공처리 된 걸로 파악된다.

(update.js)

```
function update(userId,event) {

	event.preventDefault(); // form태그 액션을 막기
	/* form 태크를 집어와서 .serialize(); 해주면 모든 input값들이 data에 담기게된다*/
	let data = $("#profileUpdate").serialize();


	$.ajax({
		type:"put",
		url:`/api/user/${userId}`,
		data:data,
		contentType:"application/x-www-form-urlencoded; charset=utf-8",
		dataType:"json" //응답은 json으로 받음
	}).done(res=>{ // HttpStatus 상태코드 200번대
		console.log("성공",res);
		//location.href = `/user/${userId}`;
	}).fail(error=>{ // HttpStatus 상태코드 200번대가 아닐시
		console.log("실패",error);
	});
}
```

HttpStatus 상태코드도 같이 넘겨줌으로써 ajax에서 성공/실패가 잘 나뉘도록 해야한다.

![Visual Studio Code](/img/%EC%83%81%ED%83%9C%EC%BD%94%EB%93%9C.png)

현재 ajax 요청 url인 UserApiController.java에서도 CMRespDto<?> 를 리턴하지 상태코드는 리턴하지 않는 상태이다. (throw 일으키는 부분)

(ControllerExceptionHandler.java)
![Visual Studio Code](/img/handler.png)

현재 ajax 요청 url인 UserApiController.java에서도 CMRespDto<?> 를 리턴하지 상태코드는 리턴하지 않는 상태이다. (here)

(ControllerExceptionHandler.java)

```
@RestController
@ControllerAdvice
public class ControllerExceptionHandler {

	@ExceptionHandler(CustomValidationException.class) // RuntimeException을 발생하는 모든 exception을 이 함수가 가로챔
	public String validationException(CustomValidationException e) {

		//CMRespDto, Script비교
		//1.클라이언트에게 응답할 때는 Script 좋음
		//2.Ajax 통신 - CMRespDto 개발자는 코드로 받는게 처리하기 쉬우니까
		//3.Android 통신 - CMRespDto 개발자는 코드로 받는게 처리하기 쉬우니까
		return Script.back(e.getErrorMap().toString());
	}


	@ExceptionHandler(CustomValidationApiException.class) // RuntimeException을 발생하는 모든 exception을 이 함수가 가로챔
	public ResponseEntity<?> validationApiException(CustomValidationApiException e) {

		return new ResponseEntity<>(new CMRespDto<>(-1,e.getMessage(),e.getErrorMap()),HttpStatus.BAD_REQUEST);
	}
}

```

CustomValidationApiException에서

```
@ExceptionHandler(CustomValidationApiException.class) // RuntimeException을 발생하는 모든 exception을 이 함수가 가로챔
	public ResponseEntity<?> validationApiException(CustomValidationApiException e) {

		return new ResponseEntity<>(new CMRespDto<>(-1,e.getMessage(),e.getErrorMap()),HttpStatus.BAD_REQUEST);
	}
```

이렇게 수정해준다

return new ResponseEntity<>(바디값,상태코드)

ResponseEntity<>를 활용하여 CMRespDto도 리턴해주고, **상태코드**도 같이 리턴될 수 있도록 처리해주었다.

여기서 BAD_REQUEST는 400번 STATUS CODE라서 이제 ajax응답시 .fail로 처리되어서 실패라고 응답이 될것이다.

![Visual Studio Code](/img/ajaxfail.png)

.fail시 js로 파싱되어 데이터가 들어오기 때문에,

다시 JSON.stringify를 통해 json로 변환해서 처리해주어야한다.

![Visual Studio Code](/img/ajaxfail2.png)

그것을 alert로 띄움

=> ControllerExceptionHandler.java에서 왜 ResponseEntity를 썼는가?

ajax통신에서는 ResponseEntity를 써야지 상태코드(http)를 전달할 수 있기 때문에 .done과 .fail에 응답할 때 분기시키기가 수월함.

**여기까지가 (2)유효성검사 해결**

---
